[finnhub]
api_key = "d2j01apr01qqoaj8vrn0d2j01apr01qqoaj8vrng"

# Optional: only if you want ChatGPT opinion
[openai]
api_key = "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"
