[finnhub]
api_key = "d20b0u1r01qmbi8rv080d20b0u1r01qmbi8rv08g"

# Optional: only if you want ChatGPT opinion
[openai]
api_key = "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"
